<testsuites id="" name="" tests="2" failures="2" skipped="0" errors="0" time="6.788242">
<testsuite name="Regrese\Doklady\Objednavky\Regrese_API.spec.ts" timestamp="2025-08-31T20:11:41.762Z" hostname="API" tests="2" failures="2" skipped="0" time="4.232" errors="0">
<testcase name="API testy objednávky › TC-XY-01: Vytvoření a ověření objednávky s dodáním za 7 dní. @regression @api @objednavky @medium" classname="Regrese\Doklady\Objednavky\Regrese_API.spec.ts" time="2.112">
<failure message="Regrese_API.spec.ts:15:13 TC-XY-01: Vytvoření a ověření objednávky s dodáním za 7 dní. @regression @api @objednavky @medium" type="FAILURE">
<![CDATA[  [API] › Regrese\Doklady\Objednavky\Regrese_API.spec.ts:15:13 › API testy objednávky › TC-XY-01: Vytvoření a ověření objednávky s dodáním za 7 dní. @regression @api @objednavky @medium 

    Error: Chyba při vytváření objednávky. Status: 400

       at ..\support\ApiClient.ts:1957

      1955 |             const errorText = await response.text();
      1956 |             logger.error(`Chyba při vytváření objednávky pro sklad ${stockId}. Status: ${response.status()}`, errorText);
    > 1957 |             throw new Error(`Chyba při vytváření objednávky. Status: ${response.status()}`);
           |                   ^
      1958 |         }
      1959 |         logger.silly(`Objednávka pro sklad ${stockId} byla úspěšně vytvořena.`);
      1960 |         // API může vrátit prázdné tělo (201, 204) nebo vytvořený objekt (200, 201)
        at ApiClient.createOrder (C:\Users\novakma\Testy_CBOS\support\ApiClient.ts:1957:19)
        at C:\Users\novakma\Testy_CBOS\tests\Regrese\Doklady\Objednavky\Regrese_API.spec.ts:42:30

    Error Context: ..\test-results\Regrese-Doklady-Objednavky-b832d-ssion-api-objednavky-medium-API\error-context.md
]]>
</failure>
<system-out>
<![CDATA[2025[0m[0m-08[0m[0m-31[0m[0m 20[0m[0m:11[0m[0m:44[0m[0m.464[0m[0m [34m[1mINFO[22m[39m[0m[0m [[37m\tests\Regrese\Doklady\Objednavky\Regrese_API.spec.ts:16[39m[0m[0m]Test TC-XY-01: Vytvoření a ověření objednávky s dodáním za 7 dní.
2025[0m[0m-08[0m[0m-31[0m[0m 20[0m[0m:11[0m[0m:44[0m[0m.573[0m[0m [32m[1mDEBUG[22m[39m[0m[0m [[37m\tests\Regrese\Doklady\Objednavky\Regrese_API.spec.ts:26[39m[0m[0m]Autenitizace úspěšně dokončena.
2025[0m[0m-08[0m[0m-31[0m[0m 20[0m[0m:11[0m[0m:44[0m[0m.575[0m[0m [32m[1mDEBUG[22m[39m[0m[0m [[37m\tests\Regrese\Doklady\Objednavky\Regrese_API.spec.ts:39[39m[0m[0m]Payload pro: POST http://192.168.130.239:8180/document {"description":"Objednávka API Test","ownerId":"1","ownerName":"ČEPRO, a.s.","suplierId":"8","SupplierName":"Banner Baterie ČR spol.s r.o.","transporterId":"434","transporterName":"AutoMax Group s.r.o","DeliveryDate":"2025-09-07T20:11:44.575Z","orderDate":"2025-08-31T20:11:44.575Z"}
2025[0m[0m-08[0m[0m-31[0m[0m 20[0m[0m:11[0m[0m:44[0m[0m.716[0m[0m [31m[1mERROR[22m[39m[0m[0m [[37m\support\ApiClient.ts:1956[39m[0m[0m]Chyba při vytváření objednávky pro sklad 230. Status: 400 {"error":"error: column \"undefined\" does not exist"}
2025[0m[0m-08[0m[0m-31[0m[0m 20[0m[0m:11[0m[0m:44[0m[0m.721[0m[0m [31m[1mERROR[22m[39m[0m[0m [[37m\tests\Regrese\Doklady\Objednavky\Regrese_API.spec.ts:58[39m[0m[0m]Chyba během testu TC-XY-01:
[97m[101m[1m Error [22m[49m[39m[0m[0m Chyba při vytváření objednávky. Status: 400[0m[0m
error stack:
  • [33m\support\ApiClient.ts[39m[0m[0m:[0m[0m:[0m[0m
    ApiClient.createOrder[0m[0m
  • [33mtask_queues[39m[0m[0m:[0m[0m:[0m[0m
    runNextTicks[0m[0m
  • [33mtimers[39m[0m[0m:[0m[0m:[0m[0m
    processImmediate[0m[0m
  • [33masync_hooks[39m[0m[0m:[0m[0m:[0m[0m
    process.callbackTrampoline[0m[0m
  • [33m\tests\Regrese\Doklady\Objednavky\Regrese_API.spec.ts[39m[0m[0m:[0m[0m:[0m[0m
    [0m[0m
  • [33m\node_modules\playwright\lib\worker\workerMain.js[39m[0m[0m:[0m[0m:[0m[0m
    [0m[0m
  • [33m\node_modules\playwright\lib\worker\testInfo.js[39m[0m[0m:[0m[0m:[0m[0m
    [0m[0m
  • [33m\node_modules\playwright\lib\worker\timeoutManager.js[39m[0m[0m:[0m[0m:[0m[0m
    TimeoutManager.withRunnable[0m[0m
  • [33m\node_modules\playwright\lib\worker\testInfo.js[39m[0m[0m:[0m[0m:[0m[0m
    TestInfoImpl._runWithTimeout[0m[0m
  • [33m\node_modules\playwright\lib\worker\workerMain.js[39m[0m[0m:[0m[0m:[0m[0m
    [0m[0m
  • [33m\node_modules\playwright\lib\worker\workerMain.js[39m[0m[0m:[0m[0m:[0m[0m
    WorkerMain._runTest[0m[0m
  • [33m\node_modules\playwright\lib\worker\workerMain.js[39m[0m[0m:[0m[0m:[0m[0m
    WorkerMain.runTestGroup[0m[0m
  • [33m\node_modules\playwright\lib\common\process.js[39m[0m[0m:[0m[0m:[0m[0m
    process.<anonymous>[0m[0m[0m[0m

[[ATTACHMENT|test-results\Regrese-Doklady-Objednavky-b832d-ssion-api-objednavky-medium-API\error-context.md]]
]]>
</system-out>
</testcase>
<testcase name="API testy objednávky › TC-XY-02: Vytvoření objednávky s jiným dodavatelem a kratší dobou dodání. @regression @api @objednavky @medium" classname="Regrese\Doklady\Objednavky\Regrese_API.spec.ts" time="2.12">
<failure message="Regrese_API.spec.ts:15:13 TC-XY-02: Vytvoření objednávky s jiným dodavatelem a kratší dobou dodání. @regression @api @objednavky @medium" type="FAILURE">
<![CDATA[  [API] › Regrese\Doklady\Objednavky\Regrese_API.spec.ts:15:13 › API testy objednávky › TC-XY-02: Vytvoření objednávky s jiným dodavatelem a kratší dobou dodání. @regression @api @objednavky @medium 

    Error: Chyba při vytváření objednávky. Status: 400

       at ..\support\ApiClient.ts:1957

      1955 |             const errorText = await response.text();
      1956 |             logger.error(`Chyba při vytváření objednávky pro sklad ${stockId}. Status: ${response.status()}`, errorText);
    > 1957 |             throw new Error(`Chyba při vytváření objednávky. Status: ${response.status()}`);
           |                   ^
      1958 |         }
      1959 |         logger.silly(`Objednávka pro sklad ${stockId} byla úspěšně vytvořena.`);
      1960 |         // API může vrátit prázdné tělo (201, 204) nebo vytvořený objekt (200, 201)
        at ApiClient.createOrder (C:\Users\novakma\Testy_CBOS\support\ApiClient.ts:1957:19)
        at C:\Users\novakma\Testy_CBOS\tests\Regrese\Doklady\Objednavky\Regrese_API.spec.ts:42:30

    Error Context: ..\test-results\Regrese-Doklady-Objednavky-fea24-ssion-api-objednavky-medium-API\error-context.md
]]>
</failure>
<system-out>
<![CDATA[2025[0m[0m-08[0m[0m-31[0m[0m 20[0m[0m:11[0m[0m:48[0m[0m.121[0m[0m [34m[1mINFO[22m[39m[0m[0m [[37m\tests\Regrese\Doklady\Objednavky\Regrese_API.spec.ts:16[39m[0m[0m]Test TC-XY-02: Vytvoření objednávky s jiným dodavatelem a kratší dobou dodání.
2025[0m[0m-08[0m[0m-31[0m[0m 20[0m[0m:11[0m[0m:48[0m[0m.219[0m[0m [32m[1mDEBUG[22m[39m[0m[0m [[37m\tests\Regrese\Doklady\Objednavky\Regrese_API.spec.ts:26[39m[0m[0m]Autenitizace úspěšně dokončena.
2025[0m[0m-08[0m[0m-31[0m[0m 20[0m[0m:11[0m[0m:48[0m[0m.221[0m[0m [32m[1mDEBUG[22m[39m[0m[0m [[37m\tests\Regrese\Doklady\Objednavky\Regrese_API.spec.ts:39[39m[0m[0m]Payload pro: POST http://192.168.130.239:8180/document {"description":"Rychlá objednávka","ownerId":"1","ownerName":"ČEPRO, a.s.","suplierId":"9","SupplierName":"Banner Baterie ČR spol.s r.o.","transporterId":"434","transporterName":"AutoMax Group s.r.o","DeliveryDate":"2025-09-01T20:11:48.220Z","orderDate":"2025-08-31T20:11:48.221Z"}
2025[0m[0m-08[0m[0m-31[0m[0m 20[0m[0m:11[0m[0m:48[0m[0m.283[0m[0m [31m[1mERROR[22m[39m[0m[0m [[37m\support\ApiClient.ts:1956[39m[0m[0m]Chyba při vytváření objednávky pro sklad 230. Status: 400 {"error":"error: column \"undefined\" does not exist"}
2025[0m[0m-08[0m[0m-31[0m[0m 20[0m[0m:11[0m[0m:48[0m[0m.285[0m[0m [31m[1mERROR[22m[39m[0m[0m [[37m\tests\Regrese\Doklady\Objednavky\Regrese_API.spec.ts:58[39m[0m[0m]Chyba během testu TC-XY-02:
[97m[101m[1m Error [22m[49m[39m[0m[0m Chyba při vytváření objednávky. Status: 400[0m[0m
error stack:
  • [33m\support\ApiClient.ts[39m[0m[0m:[0m[0m:[0m[0m
    ApiClient.createOrder[0m[0m
  • [33m\tests\Regrese\Doklady\Objednavky\Regrese_API.spec.ts[39m[0m[0m:[0m[0m:[0m[0m
    [0m[0m
  • [33m\node_modules\playwright\lib\worker\workerMain.js[39m[0m[0m:[0m[0m:[0m[0m
    [0m[0m
  • [33m\node_modules\playwright\lib\worker\testInfo.js[39m[0m[0m:[0m[0m:[0m[0m
    [0m[0m
  • [33m\node_modules\playwright\lib\worker\timeoutManager.js[39m[0m[0m:[0m[0m:[0m[0m
    TimeoutManager.withRunnable[0m[0m
  • [33m\node_modules\playwright\lib\worker\testInfo.js[39m[0m[0m:[0m[0m:[0m[0m
    TestInfoImpl._runWithTimeout[0m[0m
  • [33m\node_modules\playwright\lib\worker\workerMain.js[39m[0m[0m:[0m[0m:[0m[0m
    [0m[0m
  • [33m\node_modules\playwright\lib\worker\workerMain.js[39m[0m[0m:[0m[0m:[0m[0m
    WorkerMain._runTest[0m[0m
  • [33m\node_modules\playwright\lib\worker\workerMain.js[39m[0m[0m:[0m[0m:[0m[0m
    WorkerMain.runTestGroup[0m[0m
  • [33m\node_modules\playwright\lib\common\process.js[39m[0m[0m:[0m[0m:[0m[0m
    process.<anonymous>[0m[0m[0m[0m

[[ATTACHMENT|test-results\Regrese-Doklady-Objednavky-fea24-ssion-api-objednavky-medium-API\error-context.md]]
]]>
</system-out>
</testcase>
</testsuite>
</testsuites>